/**
 * Document URLs exposed by each investor relations index.
 *
 * Generated by scraper/discover_ir. Several of these sites build their file
 * list in the browser, so the URLs below only appear once the page has been
 * rendered, which the harvest can do and the deployment cannot.
 *
 * Discovery only. The documents themselves are downloaded and read by the
 * TypeScript side, so every figure on the dashboard comes from one reader
 * with one set of rules and this file only ever contributes addresses.
 *
 * Refresh with: npm run discover:ir
 */

export interface DiscoveredIrIndex {
  indexUrl: string;
  /** How the list was obtained: a plain request, or a rendered page. */
  mode: string;
  files: string[];
}

export const IR_DISCOVERED_AT = "2026-08-06T17:05:18.167564+00:00";

export const IR_DISCOVERED: Record<string, DiscoveredIrIndex> = {
 "TCS.NS": {
  "indexUrl": "https://www.tcs.com/investor-relations/financial-statements",
  "mode": "plain",
  "files": [
   "https://www.tcs.com/content/dam/tcs/pdf/discover-tcs/investor-relations/tcs-data-sheet/TCS-Data-Sheet-Q1FY27.xlsx",
   "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2016-17/TCS_IND_AS_Adoption.xlsx"
  ]
 },
 "HCLTECH.NS": {
  "indexUrl": "https://www.hcltech.com/investors/quarterly-results",
  "mode": "plain",
  "files": [
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCLTech-Earnings-Q1-FY27-Transcript.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCLTech-Earnings-Q3-FY26-Transcript.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/hcltech-earnings-q4-fy26-transcript.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCLTech-Earnings-Q2FY26-transcript-updated_0.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCLTech-Earnings-Q1FY26-Transcript-18.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCLTech-Earnings-Q4FY25-Transcript.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/hcl-earnings_call_transcript_19-7-2021q1fy22.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/hcltech-q1-fy26-investor-release.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/hcltech-q4-fy26-investor-release.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/hcl-tech-q2-fy25-investor-release.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCLTech-Earnings-Jan14-2022-q3.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/q3-hcl_technologies_q3_fy14_earnings_conference_call_transcript_2014.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/q2-hcl-ond13_earnings_call_transcript-jan-16-2014.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/financial_resultsq12021.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/q-4hcltech-earnings_call_transcript_q4_fy13-july_31-2013_0.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/q4hcltech-earnings-may07-2020-_new.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/q4-hcl-earnings_transcript_jul25-2012.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCLTech-call-earnings-oct14-2024-Transcript.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/q2-transcripts_hclearnings-jan25-2010.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/investor_presentation_q3fy20.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/HCL_Tech_Transcript_Q1_FY23_2022-23.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/q1_transcripts_hclearnings-oct28-2009.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/investor_presentation_q4_fy19.pdf",
   "https://www.hcltech.com/sites/default/files/documents/investor-reports/hcl_technologies_limited_q4_annual_results_fy_2015-analyst_call.pdf"
  ]
 },
 "MPHASIS.NS": {
  "indexUrl": "https://www.mphasis.com/home/corporate/investors.html",
  "mode": "plain",
  "files": [
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2027/group-overview-factsheet-q1fy27.xlsx",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2027/transcript-of-earnings-call-q1-2027.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2027/mphasis-earnings-call-presentation-q1-2027.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/mphasis-earnings-call-presentation-q2-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/transcript-of-earnings-call-q1-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/mphasis-earnings-call-presentation-q1-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/transcript-of-earnings-call-q2-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/mphasis-earnings-call-presentation-q4-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/transcript-of-earnings-call-q3-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/mphasis-earnings-call-presentation-q3-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2026/transcript-of-earnings-call-q4-2026.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/transcript-of-earnings-call-q2-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/mphasis-earnings-call-presentation-q2-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/transcript-of-earnings-call-q3-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/mphasis-earnings-call-presentation-q1-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/mphasis-earnings-call-presentation-q4-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/mphasis-earnings-call-presentation-q3-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/transcript-of-earnings-call-q4-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2025/transcript-of-earnings-call-q1-2025.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2024/transcript-of-earnings-call-q1-2024.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2024/transcript-of-earnings-call-q2-2024.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2024/transcript-of-earnings-call-q4-2024.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2023/transcript-of-earnings-call-q3-2023.pdf",
   "https://www.mphasis.com/content/dam/mphasis-com/global/en/investors/financial-results/2023/mphasis-earnings-call-presentation-q3-2023.pdf"
  ]
 },
 "TECHM.NS": {
  "indexUrl": "https://www.techmahindra.com/investors/quarterly-earnings/",
  "mode": "plain",
  "files": [
   "https://insights.techmahindra.com/investors/tml-q1fy25-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/TML%20Q3%20FY24%20Datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q1-fy-26-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q2-fy-25-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q3-fy-25-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q4-fy-25-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q3-fy-26-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q4-fy-24-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q1-fy-27-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q4-fy-26-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/tml-q2-fy-26-datasheet.xlsx",
   "https://insights.techmahindra.com/investors/Q1-FY20-Factsheet.pdf",
   "https://insights.techmahindra.com/investors/Q2-FY20-Factsheet.pdf",
   "https://insights.techmahindra.com/investors/Q1-FY19-Factsheet.pdf",
   "https://insights.techmahindra.com/investors/Q4-FY18-Factsheet.pdf",
   "https://insights.techmahindra.com/investors/Tech-Mahindra-FactSheet-Q2-FY18.pdf",
   "https://insights.techmahindra.com/investors/Q3-FY18-Consolidated-Factsheet.pdf",
   "https://insights.techmahindra.com/investors/Tech-Mahindra-FactSheet-Q1-FY18.pdf",
   "https://insights.techmahindra.com/investors/Tech-Mahindra-FactSheet-Q3-FY17.pdf",
   "https://insights.techmahindra.com/investors/Tech-Mahindra-FactSheet-Q2-FY17.pdf",
   "https://insights.techmahindra.com/investors/Tech-Mahindra-FactSheet-Q4-FY17.pdf",
   "https://insights.techmahindra.com/investors/Earnings-Call-Transcript-Q2-FY19.pdf",
   "https://insights.techmahindra.com/investors/Earnings-Call-Transcript-Q1-FY19.pdf",
   "https://insights.techmahindra.com/investors/Earnings-Call-Transcript-Q3-FY19.pdf"
  ]
 },
 "BHARTIARTL.NS": {
  "indexUrl": "https://www.airtel.in/about-bharti/equity/results",
  "mode": "plain",
  "files": [
   "https://assets.airtel.in/static-assets/cms/investor/docs/quarterly_results/2025-26/Q4/KPI-Q4-FY26-Bharti-Airtel.xlsx",
   "https://assets.airtel.in/teams/simplycms/ADTECH/docs/KPI_Q3_FY24.xlsx",
   "https://assets.airtel.in/teams/simplycms/ADTECH/docs/KPI_Q1_FY24_june2023.xlsx",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPI-Q4-FY19-Airtel-Africa_D6D9A865DD60C912654C45DD243FD7EC.xlsx",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPI-Q2-FY19-Bharti-Airtel-Consol_0C5882692C0BAB9EEDB16A62A215B042_1540549968405.xlsx",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPI-Q4-FY19-Bharti-Airtel-Consol_B66DBE40304C93FD64261380584C7D71.xlsx",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPI-Q1-FY19-BL_D65C8A1C9E1A1531BCF156E16D4EA403.xlsx",
   "http://www.airtel.in/equity-asset/Quaterly%20Results/2013-2014/first%20quarter/KPI_Q1-FY14.xls",
   "http://www.airtel.in/equity-asset/Quaterly Results/2013-2014/second quarter/KPI_Q2+FY14.xls",
   "http://www.airtel.in/equity-asset/Quaterly%20Results/2013-2014/third%20quarter/KPI_Q3-FY14.xls",
   "https://assets.airtel.in/teams/simplycms/ADTECH/docs/kpi_bharti_airtel_31102023.xlsx",
   "https://assets.airtel.in/teams/simplycms/web/docs/KPIs-Bharti-Airtel-07022023.xlsx",
   "https://assets.airtel.in/teams/simplycms/web/docs/KPIs-Bharti-Airtel-08082022.xlsx",
   "https://assets.airtel.in/teams/simplycms/web/docs/KPIs-Bharti-Airtel-31102022.xlsx",
   "https://assets.airtel.in/teams/simplycms/web/docs/KPIs-Bharti-Airtel-17052022.xlsx",
   "https://assets.airtel.in/teams/simplycms/web/docs/KPIs_Bharti_Airtel_29072020.xlsx",
   "https://assets.airtel.in/static-assets/cms/KPIs_Bharti_Airtel_19052020.xlsx",
   "https://assets.airtel.in/static-assets/cms/KPIs-Bharti-Airtel-04022020.xlsx",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPI_Q1_FY122_7EE67548EE9C3D336FB80F6A392E4C2B_1518520398397.xlsx",
   "http://www.airtel.in/equity-asset/Quaterly Results/2014-2015/fourth quarter/KPI_Q4+FY15_BL.xls",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPIs_Q1_10_488BFD97932C480E1A374E39FFB1C153_1518503367887.xlsx",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPI_Q4-FY16_BL_EE9AEE66012094E1BBAFEF25B78A9B4D.xls",
   "https://s3-ap-southeast-1.amazonaws.com/bsy/iportal/images/KPI_Q1-FY17_BL_C5AA236D57742AC9C12558D13CDF15B0_1518162260758.xlsx",
   "https://assets.airtel.in/static-assets/cms/investor/docs/bsy/iportal/images/KPIs_Q4_May_13.xls"
  ]
 },
 "RELIANCE.NS": {
  "indexUrl": "https://www.ril.com/InvestorRelations/FinancialReporting.aspx",
  "mode": "plain",
  "files": [
   "https://rilstaticasset.akamaized.net/sites/default/files/2026-07/Media_Release_RIL_Q1_FY2026-27_Financial_and_Operational_Performance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2025-07/MediaRelease-RILQ1FY2025-26FinancialandOperationalPerformance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2026-01/Media_Release_RIL_Q3_FY2025-26_Financial_and_Operational_Performance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2025-01/16012025-Media_Release-RIL_Q3_FY2024-25Financial_and_Operational_Performance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2025-10/Media_Release_RIL_Q2_FY2025-26_Financial_and_Operational_Performance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2026-04/24042026_Media_Release_RIL_Q4_FY2025-26_Financial_and_Operational_Performance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2024-07/19072024-Media-Release-RIL-Q1-FY2024-25-Financial-and-Operational-Performance_0.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2024-04/22042024-Media-Release-RIL-Q4-FY202324-Financial-and-Operational-Performance_0.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2024-10/14102024-Media-Release-RIL-Q2-FY2024-25-Financial-and-Operational-Performance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2025-10/RIL_Analyst_Meeting-2Q_FY26.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2024-10/RIL-2Q-FY25-Analyst-Presentation-14Oct24.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2026-04/FY2025-26_RIL_Analyst_Meeting.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2024-04/RIL-4Q-FY24-Analyst-Presentation-22Apr24-website.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2026-07/Presentation_for_RIL_Analyst_Meeting_v17072026.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/reports/CSR2025-26.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2025-04/25042025_Media_Release_RIL_Q4_FY2024_25_Financial_and_Operational_Performance.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/reports/RIL-Integrated-Annual-Report-2025-26.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2025-08/RIL-Integrated-Annual-Report-2024-25.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2024-08/RIL-Integrated-Annual-Report-2023-24.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2023-08/RIL-Integrated-Annual-Report-2022-23.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2022-12/RIL-AR-2021.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2022-12/AR_2021-22.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2022-12/CSR202021.pdf",
   "https://rilstaticasset.akamaized.net/sites/default/files/2022-12/Corporate%20Presentation%20May%202020.pdf"
  ]
 },
 "LTIM.NS": {
  "indexUrl": "https://www.ltimindtree.com/investors/financial-results/",
  "mode": "dynamic",
  "files": [
   "https://www.ltimindtree.com/content/dam/ltimcorporatewebsite/uploads/news-and-events/2026/07/earnings-release-factsheet-q1fy27.pdf",
   "https://www.ltimindtree.com/content/dam/ltimcorporatewebsite/uploads/investors/2026/07/earnings-call-transcript-q1fy27.pdf",
   "https://www.ltimindtree.com/content/dam/ltimcorporatewebsite/uploads/investors/2026/07/consolidated-financials-q1fy27.pdf",
   "https://www.ltimindtree.com/content/dam/ltimcorporatewebsite/uploads/investors/2026/07/standalone-financials-q1fy27.pdf"
  ]
 },
 "COFORGE.NS": {
  "indexUrl": "https://investors.coforge.com/quarter-reports",
  "mode": "plain",
  "files": [
   "https://investors.coforge.com/hubfs/Investor-Presentation-and-Factsheet-Q4FY26.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Q1-FY26-Web-Presentation-and-Factsheet.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Q2-FY26-Web-Presentation-and-Factsheet.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q1FY25.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q2FY25.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q3FY25.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q4FY24.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q2FY23.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q3FY23.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Factsheet-Q1FY23-2.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q4FY23.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Datasheet-Q2FY22.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Fact-Sheet-Q3FY22-2.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Factsheet-Q4FY22.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Coforge_Q1FY27%20Earnings%20Conference%20Call%20Transcript.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Datasheet-Q1FY22.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Coforge-Limited-Earnings-Call-Transcript-Q4FY26%20_AJ.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Datasheet-Q1FY21.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Coforge%20Earnings%20Conference%20Call%20Transcript%20Q1FY26.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Coforge-Limited-Earnings-Call-Transcript-Q2-FY26.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Coforge-Limited-Earnings-Call-Transcript-Q3-FY26.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Datasheet-Q4FY21.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Datasheet-Q2FY21.pdf?hsLang=en",
   "https://investors.coforge.com/hubfs/Datasheet-Q3FY21.pdf?hsLang=en"
  ]
 },
 "PERSISTENT.NS": {
  "indexUrl": "https://www.persistent.com/investors/quarterly-results/",
  "mode": "plain",
  "files": [
   "https://www.persistent.com/wp-content/uploads/2026/08/analyst-presentation-and-factsheet-q1fy27.pdf",
   "https://www.persistent.com/wp-content/uploads/2025/07/analyst-presentation-and-factsheet-q1fy26.pdf",
   "https://www.persistent.com/wp-content/uploads/2025/10/analyst-presentation-and-factsheet-q2fy26.pdf",
   "https://www.persistent.com/wp-content/uploads/2026/01/analyst-presentation-and-factsheet-q3fy26.pdf",
   "https://www.persistent.com/wp-content/uploads/2026/04/analyst-presentation-and-factsheet-q4fy26.pdf",
   "https://www.persistent.com/wp-content/uploads/2024/07/analyst-presentation-and-factsheet-q1fy25.pdf",
   "https://www.persistent.com/wp-content/uploads/2025/04/analyst-presentation-and-factsheet-q4fy25.pdf",
   "https://www.persistent.com/wp-content/uploads/2025/01/analyst-presentation-and-factsheet-q3fy25.pdf",
   "https://www.persistent.com/wp-content/uploads/2024/10/analyst-presentation-and-factsheet-q2fy25.pdf",
   "https://www.persistent.com/wp-content/uploads/2023/10/analyst-presentation-and-factsheet-q2fy24.pdf",
   "https://www.persistent.com/wp-content/uploads/2024/01/analyst-presentation-and-factsheet-q3fy24.pdf",
   "https://www.persistent.com/wp-content/uploads/2024/04/analyst-presentation-and-factsheet-q4fy24.pdf",
   "https://www.persistent.com/wp-content/uploads/2023/07/Analyst-Presentation-and-Fact-Sheet-Q1FY24.pdf",
   "https://www.persistent.com/wp-content/uploads/2022/07/analyst-presentation-and-factsheet-q1fy23.pdf",
   "https://www.persistent.com/wp-content/uploads/2023/01/Analyst-Presentation-and-Fact-Sheet-Q3-FY23.pdf",
   "https://www.persistent.com/wp-content/uploads/2023/04/Analyst-Presentation-and-Fact-Sheet-Q4FY23.pdf",
   "https://www.persistent.com/wp-content/uploads/2022/10/analyst-presentation-and-factsheet-q2fy23.pdf",
   "https://www.persistent.com/wp-content/uploads/2022/01/analyst-presentation-and-factsheet-q3fy22.pdf",
   "https://www.persistent.com/wp-content/uploads/2022/04/Analyst-Presentation-and-Factsheet-Q4FY22.pdf",
   "https://www.persistent.com/wp-content/uploads/2021/07/analyst-presentation-and-factsheet-q1fy22.pdf",
   "https://www.persistent.com/wp-content/uploads/2021/10/analyst-presentation-and-factsheet-q2fy22.pdf",
   "https://www.persistent.com/wp-content/uploads/2021/01/analyst-presentation-and-factsheet-q3fy21.pdf",
   "https://www.persistent.com/wp-content/uploads/2020/07/analyst-presentation-and-factsheet-q1fy21.pdf",
   "https://www.persistent.com/wp-content/uploads/2021/04/analyst-presentation-and-factsheet-q4fy21.pdf"
  ]
 },
 "CAP.PA": {
  "indexUrl": "https://investors.capgemini.com/en/financial-results/",
  "mode": "none",
  "files": []
 },
 "EXPN.L": {
  "indexUrl": "https://www.experianplc.com/investors/results-reports-presentations/results-presentations",
  "mode": "plain",
  "files": [
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/results-and-presentations/2026/Experian-fy26-full-year-results-transcript.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/results-and-presentations/2026/experian-fy26-full-year-results-final-website.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/results-and-presentations/2026/Experian-q1-fy27-trading-update-transcript.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/results-and-presentations/2026/experian-fy27-q1-trading-update-announcement.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/results-and-presentations/2023/experian-q1-fy24-trading-update.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/reports/2026/experian-annual-report-2026.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/reports/2026/sustainability-performance-data-2026.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/reports/2026/tax-report-2026.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/reports/2026/power-of-you-2026.pdf",
   "https://www.experianplc.com/content/dam/marketing/global/plc/en/assets/documents/results-and-presentations/2023/experian-ir-roadshow-deck-jan-to-mar-2023.pdf"
  ]
 },
 "ATE.PA": {
  "indexUrl": "https://www.alten.com/investors/",
  "mode": "plain",
  "files": [
   "https://www.alten.com/wp-content/uploads/2026/07/Press-release-Q2-2026-ALTEN.pdf",
   "https://www.alten.com/wp-content/uploads/2026/04/ALTEN-Press-release-Q1-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/01/Press-release-Q4-2025-ALTEN-1.pdf",
   "https://www.alten.com/wp-content/uploads/2026/04/Audiocall-transcription-Q1-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/03/Audiocall-transcription-annual-results-2025.pdf",
   "https://www.alten.com/wp-content/uploads/2026/01/Audiocall-transcription-Q4-2025.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/ALTEN-Annexe-Q2-2026-EN.pdf",
   "https://www.alten.com/wp-content/uploads/2026/02/Presentation-of-the-Annual-Results-ALTEN-2025-1.pdf",
   "https://www.alten.com/wp-content/uploads/2026/02/ALTEN-Annual-results-2025-470-Kb.pdf",
   "https://www.alten.com/wp-content/uploads/2026/04/Press-release-relating-to-the-2026-General-Meeting-and-to-the-2025-Dividend-v1.pdf",
   "https://www.alten.com/wp-content/uploads/2026/05/Press-release-relating-to-the-SBB-program__05052026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/Audiocall-transcription-S1-2026-EN.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/Half-year-liquidity-contract-statement-at-30-June-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/06/Voting-rights-2026-05-31.pdf",
   "https://www.alten.com/wp-content/uploads/2026/06/Report-on-share-repurchases-from-27-May-to-2-June-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/Report-on-share-repurchases-from-15-to-21-July-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/Report-on-share-repurchases-from-22-to-28-July-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/Report-on-share-repurchases-from-24-to-30-June-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/Report-on-share-repurchases-from-1-to-7-July-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/05/Voting-rights-2026-04-30.pdf",
   "https://www.alten.com/wp-content/uploads/2026/06/Report-on-share-repurchases-from-17-to-23-June-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/07/Voting-rights-2026-06-30.pdf",
   "https://www.alten.com/wp-content/uploads/2026/06/Report-on-share-repurchases-from-10-to-16-June-2026.pdf",
   "https://www.alten.com/wp-content/uploads/2026/05/Report-on-share-repurchases-from-6-to-12-May-2026.pdf"
  ]
 },
 "ZENSARTECH.NS": {
  "indexUrl": "https://www.zensar.com/investors",
  "mode": "plain",
  "files": [
   "https://www.zensar.com/assets/files/44UzGb8qI8JxcDiZaKEn8c/Earnings-Call-Transcript-Q4-FY26.pdf",
   "https://www.zensar.com/assets/files/5hbcJnnLv8p8QA2U7fSHob/Q4-Financial-Results-FY26.pdf",
   "https://www.zensar.com/assets/files/707tyiiTeT3OxlawhH9Fvx/Zensar-Q4FY26-Press-release.pdf",
   "https://www.zensar.com/assets/files/6KXbyaUK6SDxkt5YmsXVpm/Q4FY26-Zensar-Analyst-Presentation.pdf"
  ]
 },
 "BSOFT.NS": {
  "indexUrl": "https://www.birlasoft.com/company/investors",
  "mode": "plain",
  "files": [
   "https://www.birlasoft.com/sites/default/files/resources/downloads/investors/investor-update/q1-fy27-investor-update.pdf"
  ]
 },
 "MASTEK.NS": {
  "indexUrl": "https://www.mastek.com/investors/financial-information/",
  "mode": "plain",
  "files": [
   "https://www.mastek.com/wp-content/uploads/2026/07/Investor-Fact-Sheet-Q1FY27.xlsx",
   "https://www.mastek.com/wp-content/uploads/2025/07/Investor-Fact-Sheet-Q4FY26.xlsx",
   "https://www.mastek.com/wp-content/uploads/2025/07/Investor-Fact-Sheet-Q3FY26.xlsx",
   "https://www.mastek.com/wp-content/uploads/2025/07/Investor-Fact-Sheet-Q1FY26.xlsx",
   "https://www.mastek.com/wp-content/uploads/2025/07/Investor-Fact-Sheet-Q2FY26.xlsx",
   "https://www.mastek.com/wp-content/uploads/2024/07/Investor-Fact-Sheet-Q1FY25.xlsx",
   "https://www.mastek.com/wp-content/uploads/2024/07/Investor-Fact-Sheet-Q2FY25.xlsx",
   "https://www.mastek.com/wp-content/uploads/2025/01/Investor-Fact-Sheet-Q3FY25.xlsx",
   "https://www.mastek.com/wp-content/uploads/2024/07/Investor-Fact-Sheet-Q4FY25.xlsx",
   "https://www.mastek.com/wp-content/uploads/2023/07/Investor-Fact-Sheet-Q2FY24-1.xlsx",
   "https://www.mastek.com/wp-content/uploads/2023/07/Investor-Fact-Sheet-Q1FY24-1.xlsx",
   "https://www.mastek.com/wp-content/uploads/2023/07/Investor-Fact-Sheet-Q3FY24.xlsx",
   "https://www.mastek.com/wp-content/uploads/2024/04/Investor-Fact-Sheet-Q4FY24.xlsx",
   "https://www.mastek.com/wp-content/uploads/2022/07/Investor-Fact-Sheet-Q3FY23-1.xlsx",
   "https://www.mastek.com/wp-content/uploads/2022/07/Investor-Fact-Sheet-Q2FY23-1.xlsx",
   "https://www.mastek.com/wp-content/uploads/2022/07/Investor-Fact-Sheet-Q4FY23-1.xlsx",
   "https://www.mastek.com/wp-content/uploads/2022/07/Investor-Fact-Sheet-Q1FY23.xlsx",
   "https://www.mastek.com/wp-content/uploads/2021/10/Investor-Fact-Sheet-Q1FY22.xlsx",
   "https://www.mastek.com/wp-content/uploads/2021/10/Investor-Fact-Sheet-Q3FY22-1.xlsx",
   "https://www.mastek.com/wp-content/uploads/2021/10/Investor-Fact-Sheet-Q4FY22.xlsx",
   "https://www.mastek.com/wp-content/uploads/2021/10/Investor-Fact-Sheet-Q2FY22.xlsx",
   "https://www.mastek.com/wp-content/uploads/2021/10/Investor-Fact-Sheet-Q1FY21.xlsx",
   "https://www.mastek.com/wp-content/uploads/2021/10/Investor-Fact-Sheet-Q4FY21.xlsx",
   "https://www.mastek.com/wp-content/uploads/2021/10/Investor-Fact-Sheet-Q3FY20.xlsx"
  ]
 },
 "DATAMATICS.NS": {
  "indexUrl": "https://www.datamatics.com/about-us/investor-relations/financials",
  "mode": "plain",
  "files": [
   "https://www.datamatics.com/hubfs/Investors/Financials/2022-2023/Financials-Results-Q1-2022-2023.pdf.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2021-22/Financials-Results-Q2-2021-2022.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2021-22/Financials-Results-Q3-2021-2022.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2021-22/Financials-Results-Q4-2021-2022.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2021-22/Financials-Results-Q1-2021-2022.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2019-20/Financials-Results-Q2-2019-20.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2019-20/Financials-Results-Q1-2019-20.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2018-2019/Financial-results-quarter-ended-June-2018-Q3.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2018-2019/Financial-results-quarter-ended-June-2018-Q1.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2018-2019/Financial-results-quarter-ended-June-2018-Q2.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2018-2019/Financial-results-quarter-ended-June-2018-Q4.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2017-2018/Financial-Results-2017-18-Q4.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2017-2018/Fin-Result-Qtr-2-Sept-30-2017-Q2.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2017-2018/Financial-Results-Quarter-and-Nine-months-ended-December-31-2017-Q3.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2016-2017/Financial-Results-Quarter-June2016-Q1.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2016-2017/Financial-Results-Quarter-ended-December-31-2016-Q3.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2016-2017/Financial-Results-Quarter-September-2016-Q2.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2014-2015/Financial-results-june-2014-Q1.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2013-2014/Financial-Results-dec-Q3-2013.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2012-2013/Financial-Results-Mar-2013-Q4.pdf",
   "https://www.datamatics.com/hubfs/Investors/Subsidiaries-Accounts/2025-26/Dextara-Financials-2025-26.pdf",
   "https://www.datamatics.com/hubfs/Investors/Subsidiaries-Accounts/2025-26/DPSL-Financials-2025-26.pdf",
   "https://www.datamatics.com/hubfs/Investors/Financials/2012-2013/Financial-Results-Jan-2012-Q3.pdf",
   "https://www.datamatics.com/hubfs/Investors/Subsidiaries-Accounts/2024-25/Luminad.AI-Limited-FY-2024-25.pdf"
  ]
 },
 "RSYSTEMS.NS": {
  "indexUrl": "https://www.rsystems.com/investors-info/",
  "mode": "plain",
  "files": [
   "https://media.rsystems.com/wp-content/uploads/2026/05/CSR-Projects-approved-by-the-Board-of-Directors-2026.pdf",
   "https://media.rsystems.com/wp-content/uploads/2025/09/Annual-Report-on-CSR-Activities-2024.pdf",
   "https://media.rsystems.com/wp-content/uploads/2024/07/CSR-Report-2023.pdf",
   "https://media.rsystems.com/wp-content/uploads/2024/02/Annual-Report-on-CSR-Activities-2022.pdf",
   "https://media.rsystems.com/wp-content/uploads/2024/02/CSR-Activities-2021.pdf"
  ]
 },
 "HAPPSTMNDS.NS": {
  "indexUrl": "https://www.happiestminds.com/investors/",
  "mode": "plain",
  "files": [
   "https://www.happiestminds.com/investors/Earnings%20Call/2025-2026-Q2/Audio-Recording-of-Earnings-Call-Q2-FY26.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2026-2027-Q1/Financial%20Results%20Q1%20FY27.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2025-2026-Q2/FinancialsQ2FY26.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2025-2026-Q1/Financials-Results-Q1-FY26.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2025-2026-Q4/Financial%20Results%20Q4%20FY26.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2024-2025-Q4/Financials-ResultsQ4-FY25.pdf",
   "https://www.happiestminds.com/investors/Earnings%20Call/2021-2022-Q1/HappiestMinds_Earnings%20Call%20Transcript_July%2030,%202021.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2024-2025-Q1/Financial%20Results%20Q1%20FY25.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2024-2025-Q3/Financials-Results%20Q3-FY25.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2023-2024-Q3/Financial%20Results%20Q3%20FY24.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2023-2024-Q1/Financial%20Results%20Q1%20FY24.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2023-2024-Q4/FinancialResultsQ4FY24.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2023-2024-Q2/Financial%20Results%20Q2%20FY24.pdf",
   "https://www.happiestminds.com/investors/Press%20Release/2025-2026-Q2/Press-Release-Q2FY26.pdf",
   "https://www.happiestminds.com/investors/Press%20Release/2025-2026-Q1/Press-Release-Q1FY26.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2022-2023-Q1/Financial%20Results%20Q1%20FY23.pdf",
   "https://www.happiestminds.com/investors/Financial%20Results/2022-2023-Q2/HappiestMinds-Financial%20Results%20Q2%20FY23.pdf",
   "https://www.happiestminds.com/investors/Press%20Release/2024-2025-Q4/Press-Release-Q4FY25.pdf",
   "https://www.happiestminds.com/investors/Earnings%20Call/2026-2027-Q1/Audiorecordingofearningscall28072026.pdf",
   "https://www.happiestminds.com/investors/Earnings%20Call/2025-2026-Q3/EarningsCallTranscript13022026.pdf",
   "https://www.happiestminds.com/investors/Earnings%20Call/2026-2027-Q1/EarningsCallTranscirpt30072026.pdf",
   "https://www.happiestminds.com/investors/Earnings%20Call/2025-2026-Q3/HMAudiorecordingofearningscall10022026.pdf",
   "https://www.happiestminds.com/investors/Earnings%20Call/2025-2026-Q4/HMAudiorecordingofearningscall29052026.pdf",
   "https://www.happiestminds.com/investors/Earnings%20Call/2022-2023-Q2/HappiestMinds_Earnings%20Call%20Transcript_Oct%2026,%202022.pdf"
  ]
 },
 "SAKSOFT.NS": {
  "indexUrl": "https://www.saksoft.com/investor/financials/",
  "mode": "dynamic",
  "files": [
   "https://www.saksoft.com/wp-content/uploads/2025/08/Augmento-Labs-Private-Limited-Financials-FY-2024-25.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/08/Ceptes-Software-Private-Limited-Financials-FY-2024-25.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/08/Zetechno-Products-and-Services-Financials-FY-2024-25.pdf",
   "https://www.saksoft.com/wp-content/uploads/2022/05/SaksoftPressreleaseQ4FY22.pdf",
   "https://www.saksoft.com/wp-content/uploads/2021/08/Saksoft-Press-Release-Q1FY22.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q3-Standalone-Financials-30-01-2017.pdf",
   "https://www.saksoft.com/wp-content/uploads/2018/08/360-Logica-Standalone-Sign-Financial-.-FY-2017-18.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q2-Standalone-Financials-28-10-2016.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q4-Standalone-results-March-31-2016.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q1-Standalone-Financials-30-06-2016.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q4-Consolidated-results-March-31-2016.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q1-Consolidated-Financials-30-06-2016.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q2-Consolidated-Financials-28-10-2016.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q3-Consolidated-Financial-results-31-Dec-2015.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q2-Standalone-results-2015.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q3-Standalone-Financial-results-31-Dec-2015.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q2-Consolidated-results-2015.pdf",
   "https://www.saksoft.com/wp-content/uploads/2017/05/Q4-Consolidated-results-2014-2015.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/07/Saksoft-Solutions-Limited-Financials-March-2025.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/07/SAKSOFT-PTE-LIMITED-Financials-March-2025-Signed.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/07/Dreamorbit-Inc-Financials-March-2025.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/07/Saksoft-INC-Financials-March-2025.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/05/Saksoft_FS-Standalone-FY-2024-25.pdf",
   "https://www.saksoft.com/wp-content/uploads/2025/05/Saksoft_FS-Consolidated-FY-2024-25.pdf"
  ]
 },
 "KELLTONTEC.NS": {
  "indexUrl": "https://www.kellton.com/financial-results",
  "mode": "plain",
  "files": [
   "https://cdn.kellton.com/s3fs-public/KTSL_BM_Outcome_30062026.pdf"
  ]
 },
 "GLOB": {
  "indexUrl": "https://investors.globant.com/quarterly-earnings",
  "mode": "plain",
  "files": [
   "https://investors.globant.com/download/Fact_Sheet_Q1_2026.xlsx",
   "https://investors.globant.com/download/Fact-Sheet-Q1-2026.pdf",
   "https://investors.globant.com/download/2026_Q1_Investor_Relations_Presentation.pdf"
  ]
 }
};
