/**
 * Investor relations snapshot.
 *
 * Generated by scripts/harvest-ir.mts. Do not edit by hand.
 *
 * These publishers refuse datacentre IP ranges, so a deployed instance cannot
 * fetch them. The application attempts a live fetch on every request and uses
 * this file only when that fails, labelling the result with the date below.
 *
 * Regenerate before a deploy:
 *   node --experimental-strip-types scripts/harvest-ir.mts
 */

import type { IrQuarter } from "@/lib/feeds/ir-parse";

export const IR_SNAPSHOT_TAKEN = "2026-08-04";

export const IR_SNAPSHOT: Record<
  string,
  { name: string; irUrl: string; quarters: IrQuarter[] }
> = {
  "TCS.NS": {
    "name": "Tata Consultancy Services",
    "irUrl": "https://www.tcs.com/investor-relations/financial-statements",
    "quarters": [
      {
        "label": "Q4 FY24",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2023-24/q4/Presentations/Q4%202023-24%20Fact%20Sheet.pdf",
        "revenueInrMn": 612370,
        "revenueUsdMn": 7363,
        "inrGrowthYoyPct": 3.5,
        "ccGrowthYoyPct": 2.2,
        "operatingMarginPct": 26,
        "netMarginPct": 20.3,
        "headcount": 601546,
        "attritionLtmPct": 12.5,
        "orderBookUsdBn": 13.2,
        "confidence": 1
      },
      {
        "label": "Q1 FY25",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2024-25/q1/Presentations/Q1%202024-25%20Fact%20Sheet.pdf",
        "revenueInrMn": 626130,
        "revenueUsdMn": 7505,
        "inrGrowthYoyPct": 5.4,
        "ccGrowthYoyPct": 4.4,
        "operatingMarginPct": 24.7,
        "netMarginPct": 19.2,
        "headcount": 606998,
        "attritionLtmPct": 12.1,
        "orderBookUsdBn": 8.3,
        "confidence": 1
      },
      {
        "label": "Q2 FY25",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2024-25/q2/Presentations/Q2%202024-25%20Fact%20Sheet.pdf",
        "revenueInrMn": 642590,
        "revenueUsdMn": 7670,
        "inrGrowthYoyPct": 7.6,
        "ccGrowthYoyPct": 5.5,
        "operatingMarginPct": 24.1,
        "netMarginPct": 18.5,
        "headcount": 612724,
        "attritionLtmPct": 12.3,
        "orderBookUsdBn": 8.6,
        "confidence": 1
      },
      {
        "label": "Q3 FY25",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2024-25/q3/Presentations/Q3%202024-25%20Fact%20Sheet.pdf",
        "revenueInrMn": null,
        "revenueUsdMn": 7539,
        "inrGrowthYoyPct": null,
        "ccGrowthYoyPct": 4.5,
        "operatingMarginPct": null,
        "netMarginPct": 19.4,
        "headcount": null,
        "attritionLtmPct": 13,
        "orderBookUsdBn": 10.2,
        "confidence": 0.5714285714285714
      },
      {
        "label": "Q4 FY25",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2024-25/q4/Presentations/Q4%202024-25%20Fact%20Sheet.pdf",
        "revenueInrMn": 644790,
        "revenueUsdMn": 7465,
        "inrGrowthYoyPct": 5.3,
        "ccGrowthYoyPct": 2.5,
        "operatingMarginPct": 24.2,
        "netMarginPct": 19,
        "headcount": 607979,
        "attritionLtmPct": 13.3,
        "orderBookUsdBn": 12.2,
        "confidence": 1
      },
      {
        "label": "Q1 FY26",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2025-26/q1/Presentations/Q1%202025-26%20Fact%20Sheet.pdf",
        "revenueInrMn": 634370,
        "revenueUsdMn": 7421,
        "inrGrowthYoyPct": 1.3,
        "ccGrowthYoyPct": 3.1,
        "operatingMarginPct": 24.5,
        "netMarginPct": 20.1,
        "headcount": 613069,
        "attritionLtmPct": 13.8,
        "orderBookUsdBn": 9.4,
        "confidence": 1
      },
      {
        "label": "Q2 FY26",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2025-26/q2/Presentations/Q2%202025-26%20Fact%20Sheet.pdf",
        "revenueInrMn": null,
        "revenueUsdMn": 7466,
        "inrGrowthYoyPct": null,
        "ccGrowthYoyPct": null,
        "operatingMarginPct": 25.2,
        "netMarginPct": 19.6,
        "headcount": 593314,
        "attritionLtmPct": 13.3,
        "orderBookUsdBn": 10,
        "confidence": 0.8571428571428571
      },
      {
        "label": "Q3 FY26",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2025-26/q3/Presentations/Q3%202025-26%20Fact%20Sheet.pdf",
        "revenueInrMn": null,
        "revenueUsdMn": 7509,
        "inrGrowthYoyPct": null,
        "ccGrowthYoyPct": null,
        "operatingMarginPct": null,
        "netMarginPct": 20,
        "headcount": null,
        "attritionLtmPct": null,
        "orderBookUsdBn": 9.3,
        "confidence": 0.42857142857142855
      },
      {
        "label": "Q4 FY26",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2025-26/q4/Presentations/Q4%202025-26%20Fact%20Sheet.pdf",
        "revenueInrMn": null,
        "revenueUsdMn": 7621,
        "inrGrowthYoyPct": null,
        "ccGrowthYoyPct": null,
        "operatingMarginPct": 25.3,
        "netMarginPct": 19.4,
        "headcount": 584519,
        "attritionLtmPct": 13.7,
        "orderBookUsdBn": 12,
        "confidence": 0.8571428571428571
      },
      {
        "label": "Q1 FY27",
        "url": "https://www.tcs.com/content/dam/tcs/investor-relations/financial-statements/2026-27/q1/Presentations/Q1%202026-27%20Fact%20Sheet.pdf",
        "revenueInrMn": null,
        "revenueUsdMn": 7624,
        "inrGrowthYoyPct": null,
        "ccGrowthYoyPct": null,
        "operatingMarginPct": 24,
        "netMarginPct": 19.2,
        "headcount": 593798,
        "attritionLtmPct": 13.6,
        "orderBookUsdBn": 9.5,
        "confidence": 0.8571428571428571
      }
    ]
  }
};
