/**
 * Market snapshot.
 *
 * Generated by scripts/harvest-markets.mts. Do not edit by hand.
 *
 * The public quote endpoint rate-limits shared hosting networks and any
 * machine that bursts it, so both a serverless deployment and a workstation
 * mid-testing can be refused for minutes at a time. The application always
 * tries the live endpoint first, then the in-process last-known-good store,
 * and only then this file, labelled baseline with the date it was taken.
 *
 * Regenerate whenever the endpoint answers:
 *   node --experimental-strip-types scripts/harvest-markets.mts
 */

import type { Quote, SeriesPoint } from "@/lib/core/types";

export const MARKET_SNAPSHOT_TAKEN: string | null = null;

export const MARKET_SNAPSHOT_QUOTES: Record<string, Quote> = {};

export const MARKET_SNAPSHOT_SERIES: Record<string, SeriesPoint[]> = {};
