/**
 * Quarterly sector tracker.
 *
 * Generated by scraper/ingest_sheets from two published workbooks, both
 * shared for public read and exported over a plain request with no key.
 *
 * This is not the same material as the rest of the console, and is treated
 * differently. The dashboards compute their figures from filings on every
 * request; this is a curated quarterly record carrying what management said
 * about a quarter and why a measure moved, which no filing publishes in a
 * machine readable form. Every cell keeps its own source line, and the
 * dataset is stamped with the date it was read.
 *
 * Refresh with: npm run ingest:sheets
 */

export interface TrackerMeasure {
  prior: number | null;
  latest: number | null;
  /** Movement as the tracker states it, for example "-1.7% QoQ; 3.5% YoY". */
  status: string;
  /** What management gave as the reason. Verbatim from the tracker. */
  reason: string;
  /** Where the reason came from: a transcript, an analyst report, an article. */
  source: string;
  unit: string;
}

export interface TrackerCompany {
  name: string;
  tier: "Indian tier-1" | "Indian mid-tier";
  metrics: Record<string, TrackerMeasure>;
}

/** The two quarters the tracker compares. */
export const TRACKER_PERIODS = {"prior": "Sep'24", "latest": "Dec'24"};

export const TRACKER_TAKEN_AT = "2026-08-06T12:37:49.708415+00:00";

export const TRACKER: TrackerCompany[] = [
 {
  "name": "HCL Tech",
  "tier": "Indian tier-1",
  "metrics": {
   "revenueUsdM": {
    "prior": 3445.2,
    "latest": 3532.9,
    "status": "2.5% QoQ; 3.5% YoY",
    "reason": "Technology, Financial Services, Retail, Telecom, and ER&D verticals saw strong growth: \u2022 Strong growth in Technology and Financial Services, with significant increases in spending patterns. \u2022 Retail and CPG saw notable growth, driven by the completion of a large project. \u2022 Telecom and Media performed well due to the HPE CTG acquisition, contributing to a solid quarter. \u2022 ER&D Services showed strong sequential growth, reflecting steady demand. The company's strategic initiatives and partnerships focused on Gen AI and cloud solutions drove growth: \u2022 Successful additions to the $100 million, US$50 million, and US$20 million client deal categories YoY. \u2022 Expansion of relationships with top clients, further strengthening long-term partnerships. \u2022 Focus on Gen AI and cloud solutions drove growth in technology sectors. \u2022 Partnership expansions, such as with SAP, ServiceNow, and HPE, supported s",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 218.6,
    "latest": 220.8,
    "status": "2.2K QoQ; -3.9k YoY",
    "reason": "NA",
    "source": "",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.129,
    "latest": 0.132,
    "status": "0.3% QoQ; 0.4% YoY",
    "reason": "HCL Tech's attrition rate for Q3 FY25 increased to 13.2% on a Last Twelve Months (LTM) basis, reflecting the natural impact of a pickup in demand.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": null,
    "latest": null,
    "status": "Neutral",
    "reason": "NA",
    "source": "",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.18579472889817722,
    "latest": 0.1951088341022956,
    "status": "EBIT 90bps QoQ; -30bps YoY EBITDA 90bps QoQ",
    "reason": "Margin improvement driven by software growth, cost reductions, and favorable forex: \u2022 Software Business contributed significantly to margin improvement, reaching all-time high margins, driven by cost reductions and lower amortization benefits. \u2022 The margin improvement plan (Project Ascend) contributed positively, offsetting several factors (like the wage increase), and delivered substantial benefit to margins during the quarter. \u2022 Positive impact from favorable forex movements helped boost margins. \u2022 The discontinuation of certain products also contributed to the improved margin performance.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.2207128758852897,
    "latest": 0.229782897902573,
    "status": "EBIT 90bps QoQ; -30bps YoY EBITDA 90bps QoQ",
    "reason": "",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Infosys",
  "tier": "Indian tier-1",
  "metrics": {
   "revenueUsdM": {
    "prior": 4894.0,
    "latest": 4939.0,
    "status": "0.9% QoQ; 5.9% YoY",
    "reason": "Infosys saw strong growth, driven by Financial Services, Retail, and Healthcare and manufacturing, but faced challenges in Automotive, Communication, Resources, and Hi-Tech sectors: \u2022 Infosys saw strong YoY growth across all verticals, with notable performance in Financial Services, Retail, and Healthcare. \u2022 Financial Services in the U.S. and Europe continued to grow, driven by capital markets, mortgages, and payments. \u2022 Manufacturing showed momentum in engineering, IoT, supply chain, cloud ERP, and digital transformation (in Europe), while Retail and Consumer Products (CPG) in the U.S. benefited from improved consumer sentiment and a recovery in discretionary spending. \u2022 However, the Automotive sector in Europe remained sluggish, while the Communication and Resources sectors faced macroeconomic challenges, including rising operational pressures and muted discretionary spending. \u2022 The Hi",
    "source": "",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 317.8,
    "latest": 323.4,
    "status": "5.6K QoQ; 0.7k YoY",
    "reason": "\u2022 Infosys plans to continue its recruitment strategy by hiring both freshers and experienced professionals. \u2022 For the CY25, the company is on track to hire over 15,000 freshers, with expectations to increase this number to over 20,000 in the CY26.",
    "source": "\u2022 Transcript",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.129,
    "latest": 0.137,
    "status": "0.8% QoQ; 0.8% YoY",
    "reason": "NA",
    "source": "",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.859,
    "latest": 0.86,
    "status": "0.10% QoQ; 3.30% YoY",
    "reason": "\u2022 Infosys' utilization rate, excluding trainees, remains slightly above its preferred range, at 86%. While the company is comfortable with a target range of 83%-85%, it does not expect significant changes in utilization levels, even with ongoing hiring. The current rate reflects strong performance despite low volume growth.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.21107478545157335,
    "latest": 0.21320105284470542,
    "status": "EBIT 20bps QoQ; 80bps YoY",
    "reason": "Project Maximus, Currency gains, and Efficiency drove margins: \u2022 Project Maximus continues to contribute to a 3.6% increase in realization through value-based selling. Positive currency movements provided a 40bps tailwind, while lower provisions for post-sales support and expected credit loss provisions contributed 20bps to margin improvement. \u2022 Operational efficiency, aided by higher leave utilization, helped offset the impact of furloughs and lower working days. \u2022 However, higher third-party costs, wage hikes, variable payouts, amortization of intangibles, and large deal ramp-ups all contributed to margin pressure.",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "TCS",
  "tier": "Indian tier-1",
  "metrics": {
   "revenueUsdM": {
    "prior": 7670.0,
    "latest": 7539.0,
    "status": "-1.7% QoQ; 3.5% YoY",
    "reason": "Manufacturing saw softness, but demand for innovation grew, CME and Life Sciences face challenges: \u2022 Manufacturing experienced softness due to macro and industry-specific factors in the auto and aerospace sectors, but saw rising demand for smart manufacturing, Factory of the future, SDV, and Gen AI solutions. \u2022 The CME (Communications, Media and entertainment) industry faced ongoing challenges driven by technology-led cost optimization, though signs of an IT spending rebound are emerging. (Analyst report: Nirmal Bang) \u2022 Uncertainty around U.S. policy affected the growth potential in Life Sciences & Healthcare vertical. TCS secured strong TCV, through revenue verticals like BFSI and Retail: \u2022 TCS achieved a strong TCV of US$10.2 billion with a 1.4x book-to-bill ratio, ensuring solid revenue support ahead. \u2022 Key contributors were vertical like BFSI, Retail. \u2022 Regions like North America. \u2022 ",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 612.7,
    "latest": 607.4,
    "status": "-5.3K QoQ; 5.8k YoY",
    "reason": "\u2022 The reduction in headcount is the result of several factors, including productivity, utilization, and cost efficiency initiatives. \u2022 The company stated that 11,000 new employees were onboarded in Q1 and Q2 of FY25, and it remains on track to hire 40,000 campus recruits this year.",
    "source": "\u2022 News Article: Business standard",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.123,
    "latest": 0.13,
    "status": "0.7% QoQ; -0.3% YoY",
    "reason": "The company stated that over 25,000 associates were promoted this quarter, bringing the total number of promotions for the financial year to more than 110,000. The company remains committed to investing in employee upskilling and overall well-being.",
    "source": "\u2022 News Article: TOI",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": null,
    "latest": null,
    "status": "Neutral",
    "reason": "NA",
    "source": "",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.241,
    "latest": 0.245,
    "status": "EBIT 40bps QoQ; -50bps YoY",
    "reason": "Improved productivity, utilization, and pyramid optimization positively impacted margins: \u2022 Operating efficiency boosted by enhanced productivity across operations. \u2022 Higher utilization and pyramid optimization contributed positively to margin expansion. Margins remained positive despite headwinds: \u2022 Headwinds such as seasonality and furloughs impacted margins in Q3'24. \u2022 Increased expenses from third-party items and investments in talent have put slight pressure on margins.",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Tech Mahindra",
  "tier": "Indian tier-1",
  "metrics": {
   "revenueUsdM": {
    "prior": 1588.7,
    "latest": 1567.5,
    "status": "-1.3% QoQ; -0.3% YoY",
    "reason": "Currency Fluctuations Impact: \u2022 In Q3, the company faced significant cross-currency headwinds, which negatively affected reported revenue. \u2022 The impact resulted in a decline of 1.3% QoQ and 0.4% YoY. Despite this, the company saw growth in below-mentioned areas, mitigating some of the negative effects. Revenue Growth Across Verticals and Geographies: \u2022 The company experienced healthy revenue growth in key sectors such as Communications, BFSI (Banking, Financial Services, and Insurance), and Healthcare and Life Sciences. \u2022 Geographically, there were pockets of strong demand in prioritized markets, including North America, Europe, and APJ, contributing positively to overall revenue performance. New Deals and Business Expansion: \u2022 New deal wins amounted to US$745 million in Q3 FY25, driven by large and multi-tower deals, particularly in the Telecom and Manufacturing sectors. \u2022 The company\u2019s",
    "source": "\u2022 Transcript",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 154.3,
    "latest": 150.5,
    "status": "-3.8K QoQ; 4.3k YoY",
    "reason": "Headcount Reduction Driven by Efficiency Gains: \u2022 The reduction in headcount is linked to the company\u2019s focus on improving efficiency, particularly through \"Project Fortius\". \u2022 This project aims to enhance the profitability of fixed-price projects. As part of this, the company has worked on optimizing contracts, increasing productivity, and using automation. \u2022 Even though new employees (freshers) were added throughout the year, the headcount in the IT department has decreased. This is because the company identified areas where costs could be reduced by adjusting staffing levels, particularly in tough contracts and regions.",
    "source": "\u2022 Transcript",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.11,
    "latest": 0.11,
    "status": "0.0% QoQ; 0.1% YoY",
    "reason": "NA",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.86,
    "latest": 0.86,
    "status": "0.0% QoQ; -2.00% YoY",
    "reason": "Improving Capacity Utilization through Efficiency and Automation: \u2022 The company is focusing on several operating levers to improve capacity utilization. This includes enhancing efficiency in resource utilization, integrating automation, lean practices, and AI into various fixed-price programs, and reducing reliance on contractors. \u2022 These measures are designed to optimize operations and make better use of available capacity.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.096,
    "latest": 0.101,
    "status": "EBIT 50bps QoQ; 470bps YoY EBITDA 50bps QoQ",
    "reason": "Margin Expansion Despite Challenges: \u2022 The company reported EBIT margins of 10.2%, reflecting a 60 basis point expansion from the previous quarter. \u2022 This growth was achieved despite significant currency headwinds and ongoing investments. The margin improvement is attributed to efficient delivery, pricing excellence, and cost optimization initiatives under Project Fortius. Key Margin Drivers: \u2022 Key levers contributing to margin improvement include delivery-led growth, effective pricing strategies, pyramid optimization, and increased productivity in fixed-price projects through automation. \u2022 Additionally, the reversal of furloughs in Q4 is expected to further support margin growth.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.131,
    "latest": 0.136,
    "status": "EBIT 50bps QoQ; 470bps YoY EBITDA 50bps QoQ",
    "reason": "",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Wipro",
  "tier": "Indian tier-1",
  "metrics": {
   "revenueUsdM": {
    "prior": 2662.662362666667,
    "latest": 2633.6184,
    "status": "-1.1% QoQ; -0.8% YoY",
    "reason": "Wipro\u2019s 3QFY25 revenue showed slight sequential growth (up by 0.1%) in CC terms but a minor YoY decline (down by 0.7%) Revenue growth was challenged in Europe, APMEA, and specific sectors, while the Americas performed well: \u2022 During Q3'24, revenue showed flat growth, with headwinds observed in Europe and APMEA. Across revenue verticals such as energy, manufacturing, resources, and technology and communications, there was a notable YoY decline, despite some QoQ growth. \u2022 However, the Americas led regional performance, driven by steady demand in health, technology, and communications. Healthcare, BFSI, and manufacturing sectors performed well, while the consumer sector saw slight YoY growth despite a small quarterly decline. Capco saw growth, supported by strong TCV and pipeline: \u2022 Capco business experienced improved demand, with notable year-on-year growth in both order book and revenue. ",
    "source": "\u2022 Transcript",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 233.9,
    "latest": 232.7,
    "status": "-1.2K QoQ; -7.5k YoY",
    "reason": "\u2022 The company has resumed active hiring, with plans to hire 10,000 to 12,000 campus recruits quarterly next fiscal, along with lateral hiring. \u2022 The company will continue to assess hiring needs in relation to utilization, demand, and attrition. However, no immediate challenges are expected in the hiring process.",
    "source": "\u2022 Transcript",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.145,
    "latest": 0.153,
    "status": "0.8% QoQ; 1.1% YoY",
    "reason": "\u2022 Attrition is expected to decline in the coming quarters, as net new resignations have been decreasing. \u2022 Wipro remains committed to investing in AI education, with 50,000 employees now holding advanced AI certifications.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.864,
    "latest": 0.835,
    "status": "-2.90% QoQ; -0.50% YoY",
    "reason": "NA",
    "source": "",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.168,
    "latest": 0.175,
    "status": "EBIT 70bps QoQ; 150bps YoY",
    "reason": "Operating margins reached a 12-quarter high of 17.5%, reflecting a 0.7% QoQ and 1.5% YoY improvement the following were the key drivers for margin improvement: \u2022 Execution rigor: Improved execution in both core business and consulting (including Capco) drove margin expansion. \u2022 Utilization and offshoring: Optimized utilization rates and increased offshoring positively impacted margins. \u2022 Fixed-price productivity: Enhanced productivity from fixed-price contracts contributed to margin improvement. \u2022 Overhead reductions: Conscious cuts in overheads, including G&A expenses, further supported margin growth. \u2022 Wage revision impact: The impact of two months of incremental wage revision in Q3 was absorbed, but this was a factor to consider during the quarter. However, this is now fully behind the company, and the wage revision impact is no longer a burden moving forward.",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Coforge",
  "tier": "Indian mid-tier",
  "metrics": {
   "revenueUsdM": {
    "prior": 369.4,
    "latest": 397.1,
    "status": "7.5% QoQ; 40.8% YoY",
    "reason": "Q3 traditionally experiences seasonality and weaker performance compared to other quarters, yet the company still saw growth, despite these challenges. Growth driven by Cloud, Infrastructure, and key geographies: \u2022 Growth driven primarily by Cloud & Infrastructure services and the \u2018Others\u2019 (include Healthcare, Retail, Hi-Tech and Manufacturing) vertical. \u2022 The company also saw strong performance in North America and EMEA geographies. Large deals and new logos helped boost order book: \u2022 Secured multiple large deals and significant new logo additions, contributing to a healthy order book. \u2022 The executable order book reached an all-time high, reflecting a strong sales pipeline and deal wins. Cigniti business saw growth: \u2022 The company also experienced positive sequential growth in Cigniti business, with notable improvements in revenue and margin.",
    "source": "\u2022 Transcript",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 32.5,
    "latest": 33.1,
    "status": "0.6K QoQ; 8.5k YoY",
    "reason": "NA",
    "source": "",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.117,
    "latest": 0.119,
    "status": "0.2% QoQ; -0.2% YoY",
    "reason": "Workforce Investment & Upskilling: \u2022 Coforge continues to invest in upskilling its workforce, particularly in AI-based technologies. \u2022 Through the AI Spark initiative, a significant portion of the workforce has been certified in AI tools and foundational concepts, enhancing capabilities across the company.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.822,
    "latest": 0.813,
    "status": "-0.9% QoQ; 1.9% YoY",
    "reason": "Company aims for stable utilization and growth readiness: \u2022 The company seeks to maintain stable utilization levels to meet demand and support growth, with a target utilization range of 83-84%. \u2022 The company prefers to maintain a bench of resources ready to be deployed to support growth.",
    "source": "",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.118,
    "latest": 0.118,
    "status": "EBIT 0bps QoQ; 200bps YoY EBITDA -20bps QoQ; -170bps YoY",
    "reason": "Coforge's EBITDA improved, driven by strong performance, while Cigniti saw significant margin expansion: \u2022 EBITDA margin showed improvement despite the seasonally soft quarter, with a notable increase when excluding Cigniti, reflecting strong performance. \u2022 Cigniti also experienced significant margin expansion on both a QoQ and YoY basis. Management expects the reversal of furlough impacts in the next quarter, which is anticipated to provide a tailwind. Furloughs and amortization impacted margins in 3Q: \u2022 Furloughs impacted the 3Q margin, particularly in the BFS and insurance verticals. \u2022 EBIT margins were affected by amortization of intangibles related to the purchase price.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.158,
    "latest": 0.156,
    "status": "EBIT 0bps QoQ; 200bps YoY EBITDA -20bps QoQ; -170bps YoY",
    "reason": "",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Happiest Minds",
  "tier": "Indian mid-tier",
  "metrics": {
   "revenueUsdM": {
    "prior": 62.280338400000005,
    "latest": 62.635580000000004,
    "status": "0.6% QoQ; 26.8% YoY",
    "reason": "The company achieved moderate overall revenue growth, driven by solid performance in key verticals and regions. Americas led revenue growth, along with India, APAC and RoW showing notable growth: \u2022 Americas accounted for a major portion of the revenue, with moderate growth. \u2022 For India, growth driven by the regional demand, particularly from local clients. \u2022 Both APAC and RoW regions saw notable growth, driven by strategic partnerships and market opportunities. \u2022 However, Europe witnessed slower growth compared to other regions, with a slight decline in QoQ revenue. BFSI, healthcare, retail, and HiTech saw significant growth: \u2022 BFSI sector saw a significant rise in revenue, largely due to acquisitions and new opportunities in banking and reinsurance. \u2022 Healthcare vertical revenue grew, with a positive YoY increase. \u2022 Retail and HiTech witnessed Positive shifts in retail, driven by digita",
    "source": "\u2022 Transcript",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 6.58,
    "latest": 6.63,
    "status": "0.05k QoQ; 1.38k YoY",
    "reason": "\u2022 The company experienced slight headcount growth due to the acquisition, which brought in a talented workforce of over 90 employees. (Analyst report: KR Choksey)",
    "source": "\u2022 Analyst Report: KR Choksey",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.144,
    "latest": 0.153,
    "status": "0.9% QoQ; 1.2% YoY",
    "reason": "\u2022 Attrition has seen a small uptick, which is believed to be a seasonal phenomenon. Attrition expected to improve in upcoming quarters: \u2022 The company anticipates an improvement in the attrition rate from the next quarter.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.763,
    "latest": 0.78,
    "status": "1.7% QoQ; 1.3% YoY",
    "reason": "\u2022 Management noted that efforts to boost utilization are underway, with a target rate of 80%.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.179,
    "latest": 0.175,
    "status": "EBIT -40bps QoQ -260bps YoY EBITDA -60bps QoQ -310bps YoY",
    "reason": "Sonata Software's margins were positively impacted by favorable foreign currency conditions, which benefited overall performance: \u2022 Efforts to increase utilization are expected to further improve margins, with a target utilization rate of 80%. \u2022 Additionally, growth in non-linear business, particularly in banking sector licensing, directly contributed to margin expansion. (Analyst report: KR Choksey) Increased pay and benefits: \u2022 Efforts to meet industry standards for compensation have added to operational costs. Lead-lag effect of sales engine: \u2022 The delayed impact of the new sales initiatives is temporarily affecting margins.",
    "source": "\u2022 Transcript \u2022 Analyst Report: KR Choksey",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.217,
    "latest": 0.211,
    "status": "EBIT -40bps QoQ -260bps YoY EBITDA -60bps QoQ -310bps YoY",
    "reason": "",
    "source": "\u2022 Transcript \u2022 Analyst Report: KR Choksey",
    "unit": "share"
   }
  }
 },
 {
  "name": "LTIMindtree",
  "tier": "Indian mid-tier",
  "metrics": {
   "revenueUsdM": {
    "prior": 1126.6,
    "latest": 1138.7,
    "status": "1.1% QoQ; 5.1% YoY",
    "reason": "BFSI led growth, with manufacturing deals further diversifying the business: \u2022 All verticals saw YoY growth, with BFSI leading, driven by strong performance in both BFS and Insurance. LTIMindtree secured significant deals in BFSI, including one leveraging its proprietary \u201cAI in infrastructure\u201d platform. \u2022 Additionally, a new large deal in the manufacturing vertical helped further diversify the business. LTIMindtree achieved a record TCV, added new logos, and secured strong renewals: \u2022 The company signed record TCV, added 17 new logos, and secured strong vendor consolidation deals and long-term renewals, particularly in BFSI. AI drove innovation by scaling deals, and efficiencies: \u2022 The company's AI framework continues to drive innovation, with AI becoming a key factor in securing new deals and optimizing existing operations. \u2022 Cost reduction measures and vendor consolidation are fuelling",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 84.4,
    "latest": 86.8,
    "status": "2.4K QoQ; 4.3k YoY",
    "reason": "Company continues to grow workforce with freshers and new hires: \u2022 The company continues to grow its workforce to support business growth, marking the third consecutive quarter of employee additions. A significant number of new hires have been made, contributing to an increase in total headcount. \u2022 In alignment with the strategy to broaden the pyramid, the company successfully onboarded a substantial number of freshers this quarter, further strengthening the workforce.",
    "source": "\u2022 Transcript",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.145,
    "latest": 0.143,
    "status": "-0.2% QoQ; 0.1% YoY",
    "reason": "NA",
    "source": "",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.877,
    "latest": 0.854,
    "status": "-2.3% QoQ; -2.0% YoY",
    "reason": "Bench capacity strengthening supports future growth and utilization remains within target: \u2022 Utilization decreased slightly from the previous quarter, in line with the strategy to build bench capacity and prepare for future growth. However, this is expected to improve as newly won deals are fully executed. \u2022 The current utilization aligns with the comfortable target range (85% to 86%), with hiring and utilization levels depending on market conditions and demand.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.15458660645188652,
    "latest": 0.13755447215062783,
    "status": "EBIT -170bps QoQ; -160bps YoY EBITDA -150bps QoQ; -110bps YoY",
    "reason": "EBIT margin down due to wage hikes, partially offset by cost optimization: \u2022 EBIT margin decreased by 170 bps compared to the previous quarter, primarily driven by wage hikes, effective from October 1'24, contributed a significant portion to the margin decline, estimated at approximately 220 bps. \u2022 Notwithstanding the seasonal effects of furloughs and reduced working days, the company's continuous focus on cost optimization drove a 50 bps sequential improvement in margins.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.18014608444910898,
    "latest": 0.16492252274632802,
    "status": "EBIT -170bps QoQ; -160bps YoY EBITDA -150bps QoQ; -110bps YoY",
    "reason": "",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Mphasis",
  "tier": "Indian mid-tier",
  "metrics": {
   "revenueUsdM": {
    "prior": 421.1,
    "latest": 419.3,
    "status": "-0.4% QoQ; 4.2% YoY",
    "reason": "BFS and TMT grew along with AI led deals driving deals, while Logistics and Healthcare faced challenges: \u2022 BFS (Banking, Financial Services) saw strong wallet share gains and continued growth, particularly in the mortgage sector. \u2022 TMT (Telecom, Media, Technology) maintained solid deal-to-revenue transitions and continued success in securing new deals. \u2022 Additionally, new-gen deal wins improved QoQ, with AI-driven transformation enhancing deal sizes and client engagement. (Analyst report: Nirmal Bang) \u2022 However, Logistics sector saw a broad-based decline across customers, driven by macroeconomic challenges and supply chain disruptions, although the airline segment grew from a small base. \u2022 Healthcare faced headwinds due to difficulties in the payer business. The company closed large deals enhancing pipeline growth: \u2022 The company closed several large deals and saw a notable improvement in",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 31.6,
    "latest": 31.2,
    "status": "-0.4K QoQ; -2.8k YoY",
    "reason": "NA",
    "source": "",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": null,
    "latest": null,
    "status": "Neutral",
    "reason": "NA",
    "source": "",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.805,
    "latest": 0.8,
    "status": "-0.5% QoQ; 3.5% YoY",
    "reason": "Mphasis' utilization remained lower than the other industry peers due to the continued restructuring of the workforce, especially in the pyramid at the lower levels. While improvements are being made, this remains a work in progress. Utilization improved due to higher onsite headcount and AI-driven operations: \u2022 While headcount went down significantly, it didn't cause revenue to decrease in the same proportion, resulting in non-linear outcomes. \u2022 This non-linearity is due to three main factors: a) Utilization improved from 68% to 74%, b) a higher onsite headcount, which typically boosts utilization, and c) AI-driven operations reducing manual effort by approximately 30-40%. (Analyst report: Nirmal Bang) Utilization trend remains stable however, changes in demand can impact the outlook: \u2022 There has been no significant change in the utilization trend recently, with expectations to maintain",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.154,
    "latest": 0.153,
    "status": "EBIT -10bps QoQ; 40bps YoY EBITDA 70bps QoQ; 100bps YoY",
    "reason": "EBIT margin aligned with expectations, furlough impact lower: \u2022 EBIT margin for 3QFY25 was in line with consensus and slightly higher than expectations, driven by lower direct costs, especially employee-related expenses. \u2022 The furlough impact for 3Q was lower than anticipated, and a healthy recovery is expected in 4Q, with no major furlough expansions anticipated. (Analyst report: Nirmal Bang)",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.183,
    "latest": 0.19,
    "status": "EBIT -10bps QoQ; 40bps YoY EBITDA 70bps QoQ; 100bps YoY",
    "reason": "",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "share"
   }
  }
 },
 {
  "name": "Persistent Systems",
  "tier": "Indian mid-tier",
  "metrics": {
   "revenueUsdM": {
    "prior": 345.5,
    "latest": 360.2,
    "status": "4.3% QoQ; 19.9% YoY",
    "reason": "Healthcare, BFSI, and Hi-Tech showed strong growth: \u2022 Healthcare & Life Sciences drove strong growth, marking its first quarter to exceed a US$100 million quarterly run rate. BFSI also experienced solid growth, while Hi-Tech showed positive performance as well. North America, ROW, India, and Europe showed growth: \u2022 North America experienced strong growth and Rest of the World (ROW) saw significant growth on a low base. India and Europe also contributed positively, with Europe returning to growth after three consecutive quarters of decline. Growth driven by strong bookings, platformization, and seasonality: \u2022 There has been consistent sequential growth for 19 consecutive quarters, with strong quarterly bookings (TCV) and ACV, reaching record highs. \u2022 Revenue has increased from outcome-based engagements and platformization. The high TCV was primarily driven by seasonality and large renewal",
    "source": "\u2022 Transcript \u2022 Analyst report: Nirmal Bang",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 23.2,
    "latest": 23.9,
    "status": "0.7K QoQ; 0.6k YoY",
    "reason": "Strategic workforce development: \u2022 The company is focusing on a two-tiered workforce structure\u2014one focused on immediate market share gains and another dedicated to building future-ready platforms. \u2022 Over the coming years, the workforce pyramid will evolve, with a shift towards more outcome-driven business models and less traditional structures.",
    "source": "\u2022 Transcript",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.12,
    "latest": 0.126,
    "status": "0.6% QoQ; 0.7% YoY",
    "reason": "\u2022 Management stated that, investment in training is key, with a focus on equipping employees with the necessary skills related to proprietary and partner-developed technologies, including Hyperscalers.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.848,
    "latest": 0.874,
    "status": "2.6% QoQ; 5.9% YoY",
    "reason": "Utilization at peak levels, with efforts to manage capacity through headcount adjustments in line with current contracts: \u2022 While utilization is currently at peak levels, the comfortable range for utilization is typically in the 83% to 85% range. There is confidence that the short-term high utilization will continue without dropping significantly. \u2022 The management hinted that there are ongoing efforts to manage capacity with appropriate headcount additions, in alignment with current contract work.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.14,
    "latest": 0.149,
    "status": "EBIT 90bps QoQ; 40bps YoY EBITDA 100bps QoQ; -10bps YoY",
    "reason": "Improved utilization, pricing, currency, and cost reductions boosted margins: \u2022 Improved utilization and contractor cost rationalization with a large healthcare customer, along with operational initiatives, contributed to margin improvement. \u2022 A favorable currency movement, driven by a stronger US dollar, supported margins. \u2022 Enhanced pricing on certain contracts boosted margins. \u2022 Reduction in ESOP costs provided additional margin benefit.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.166,
    "latest": 0.176,
    "status": "EBIT 90bps QoQ; 40bps YoY EBITDA 100bps QoQ; -10bps YoY",
    "reason": "",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Sonata Software",
  "tier": "Indian mid-tier",
  "metrics": {
   "revenueUsdM": {
    "prior": 259.0632364666667,
    "latest": 335.44922,
    "status": "29.5% QoQ; 12.0% YoY",
    "reason": "International services revenue grew, but TMT segment faced setbacks: \u2022 The international services revenue showed strong growth, with a notable QoQ and YoY increase in both USD and constant currency terms. The broad-based growth was particularly strong across sectors such as BFS, Healthcare, and the US. \u2022 However, International revenue faced some setbacks due to an unplanned ramp-down and a one-time discount offered to a major TMT client, which affected performance in the short term. \u2022 This issue impacted the TMT vertical, particularly in the international segment, and will likely have a full effect in the next quarter. Domestic revenue grew due to broad-based demand: \u2022 Domestic revenue exhibited healthy growth, with a significant sequential increase driven by broad-based demand across BFS, Healthcare, and the US markets. Large deal pipeline with majority focus on cloud and data solutions",
    "source": "\u2022 Transcript",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 6.4,
    "latest": 6.6,
    "status": "0.2k QoQ; 0.5k YoY",
    "reason": "Sonata Software made significant strides in its hiring and talent development efforts during the quarter, which included: \u2022 Onboarding 182 new team members, implementing compensation increases for mid and senior management, and continuing its campus recruitment by bringing on nearly 100 fresh graduates. \u2022 The company also prioritized acquiring new skills, especially in emerging areas like generative AI, through strategic university partnerships.",
    "source": "\u2022 Transcript",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.13,
    "latest": 0.14,
    "status": "1.0% QoQ; 2.0% YoY",
    "reason": "\u2022 Sonata Software is focusing on AI integration and workforce upskilling, with a large portion of its employees undergoing Gen-AI Level 1 training. \u2022 This demonstrates the company's long-term commitment to enhancing capabilities and preparing for the future by leveraging AI across operations.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.87,
    "latest": 0.87,
    "status": "0% QoQ; 1.2% YoY",
    "reason": "NA",
    "source": "-",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.06521982494998803,
    "latest": 0.046187020497469075,
    "status": "EBIT -190bps QoQ; EBITDA -230bps QoQ;",
    "reason": "EBITDA margins were impacted by client run down: \u2022 EBITDA margins were impacted by a sudden ramp down, including a client run down, one-time discounts, severance payouts, and nearshore cost reductions. However margin were positively offset by SG&A savings, forex and tax benefits: \u2022 Wage hike impact was offset by SG&A savings, contributing to margin stability. \u2022 International business benefited from favorable forex, one-time tax benefits, and the unwinding of interest on deferred consideration.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.08039152042843566,
    "latest": 0.057538544880205746,
    "status": "EBIT -190bps QoQ; EBITDA -230bps QoQ;",
    "reason": "",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 },
 {
  "name": "Zensar",
  "tier": "Indian mid-tier",
  "metrics": {
   "revenueUsdM": {
    "prior": 156.21562738070114,
    "latest": 157.0,
    "status": "0.5% QoQ; 8.5% YoY",
    "reason": "Zensar reports modest growth driven by key segments \u2022 Zensar experienced moderate overall growth, with a 0.7% QoQ CC revenue increase. \u2022 This performance was driven by the Manufacturing & Consumer services segment, which grew by 6.5% QoQ CC, and the Healthcare & Lifesciences segment, which saw a 3.2% QoQ CC increase. \u2022 However, the Telecom, Media, and Technology (TMT) segment declined by 3.5% QoQ CC, impacted by client-specific furloughs. Recovery in discretionary spending: \u2022 Management highlighted that client's discretionary spending is gradually recovering, in line with growing client interest in emerging technologies like GenAI and Agentic AI. \u2022 The company has proactively embraced these trends through its innovative AI solutions. Strong booking momentum: \u2022 Zensar reached its highest-ever order book of USD 205 million in 3Q, with a book-to-bill ratio of 1.3x, driven by broad-based dea",
    "source": "\u2022 Transcript",
    "unit": "USD m"
   },
   "headcountK": {
    "prior": 10.24,
    "latest": 10.517,
    "status": "0.3k QoQ",
    "reason": "Increase in workforce, anticipates continued hiring momentum: \u2022 At the end of 3QFY25, Zensar\u2019s total number of employees stood at 10,517, reflecting a net addition of 277 employees QoQ. \u2022 The company added 795 gross employees during the quarter. \u2022 As growth continues, Zensar expects to maintain strong hiring momentum, including campus recruitment.",
    "source": "\u2022 Transcript",
    "unit": "thousands"
   },
   "attritionPct": {
    "prior": 0.101,
    "latest": 0.1,
    "status": "-0.1% QoQ",
    "reason": "Zensar achieves record low Attrition rate \u2022 LTM attrition for 3QFY25 stood at 10%, marking a 10bps decrease QoQ and representing the lowest attrition rate in the company\u2019s history.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "utilisationPct": {
    "prior": 0.828,
    "latest": 0.829,
    "status": "0.1% QoQ",
    "reason": "Utilization slightly improves and room for further gains \u2022 Utilization for 3QFY25 was 82.9%, reflecting a 10bps QoQ increase, despite the quarter typically being a low utilization period due to seasonal furloughs. \u2022 Management noted there is potential for further improvement in utilization in the upcoming quarters.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitMarginPct": {
    "prior": 0.13091758034244597,
    "latest": 0.13757961783439493,
    "status": "EBIT 67bps QoQ -80bps YoY EBITDA 20bps QoQ -160bps YoY",
    "reason": "Improvement in margins driven by operational efficiencies: \u2022 Zensar's margin were supported by higher utilization, net furlough impact, and operational efficiencies such and other factors, including a exchange benefit. \u2022 However, SG&A increased due to a one-time saving from ESOP and sales commission, alongside investments in sales and infrastructure.",
    "source": "\u2022 Transcript",
    "unit": "share"
   },
   "ebitdaMarginPct": {
    "prior": 0.1536609196581816,
    "latest": 0.15541401273885355,
    "status": "EBIT 67bps QoQ -80bps YoY EBITDA 20bps QoQ -160bps YoY",
    "reason": "",
    "source": "\u2022 Transcript",
    "unit": "share"
   }
  }
 }
];

/** Prose sections of the tracker, kept as rows of cells. */
export const TRACKER_NARRATIVE: Record<string, string[][]> = {
 "aiAndGenAi": [],
 "mergersAndAcquisitions": [],
 "geographicExpansion": [],
 "managementAnnouncements": [],
 "revenueGuidance": [
  [
   "Note:",
   "Primarily, the reasons and commentary provided have been sourced from the respective company's earnings call transcript. Additionally, we have incorporated insights from analysts, with their names enclosed in brackets whenever cited."
  ]
 ],
 "marginGuidance": [
  [
   "Note:",
   "Primarily, the reasons and commentary provided have been sourced from the respective company's earnings call transcript. Additionally, we have incorporated insights from analysts, with their names enclosed in brackets whenever cited."
  ]
 ]
};
