import { writeFileSync } from "node:fs";
import { UNIVERSE, INDICES } from "../lib/data/universe.ts";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const CHARTED = ["ACN", "TCS.NS", "NVDA", "MSFT", "^NDX", "^CNXIT"];
const SPACING_MS = 600;

interface Meta {
  currency?: string;
  symbol?: string;
  shortName?: string;
  longName?: string;
  regularMarketPrice?: number;
  chartPreviousClose?: number;
  previousClose?: number;
  regularMarketDayHigh?: number;
  regularMarketDayLow?: number;
  fiftyTwoWeekHigh?: number;
  fiftyTwoWeekLow?: number;
  marketState?: string;
  fullExchangeName?: string;
  regularMarketTime?: number;
}

async function chart(symbol: string, range: string, interval: string) {
  const url =
    `https://query2.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}` +
    `?range=${range}&interval=${interval}`;
  const res = await fetch(url, {
    headers: { "User-Agent": UA, Accept: "application/json" },
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const json = (await res.json()) as {
    chart: {
      result: Array<{
        meta: Meta;
        timestamp?: number[];
        indicators?: {
          quote?: Array<{ close?: Array<number | null> }>;
          adjclose?: Array<{ adjclose?: Array<number | null> }>;
        };
      }> | null;
      error: { description?: string } | null;
    };
  };
  if (json.chart.error || !json.chart.result?.length) {
    throw new Error(json.chart.error?.description ?? "no result");
  }
  return json.chart.result[0];
}

async function main() {
  const symbols = [
    ...UNIVERSE.map((c) => c.symbol),
    ...INDICES.map((i) => i.symbol),
  ];

  const quotes: Record<string, unknown> = {};
  const series: Record<string, Array<{ t: number; close: number }>> = {};
  let ok = 0;

  for (const symbol of symbols) {
    try {
      const r = await chart(symbol, "1d", "1d");
      const m = r.meta;
      const price = m.regularMarketPrice ?? 0;
      const prev = m.chartPreviousClose ?? m.previousClose ?? null;
      quotes[symbol] = {
        symbol: m.symbol ?? symbol,
        name: m.longName ?? m.shortName ?? symbol,
        currency: m.currency ?? "USD",
        price,
        previousClose: prev,
        changePct:
          prev && prev > 0
            ? Number((((price - prev) / prev) * 100).toFixed(2))
            : null,
        dayHigh: m.regularMarketDayHigh ?? null,
        dayLow: m.regularMarketDayLow ?? null,
        fiftyTwoWeekHigh: m.fiftyTwoWeekHigh ?? null,
        fiftyTwoWeekLow: m.fiftyTwoWeekLow ?? null,
        marketState: m.marketState ?? null,
        exchange: m.fullExchangeName ?? null,
        asOf: m.regularMarketTime ?? null,
      };
      ok++;
      console.log(`  ok   ${symbol.padEnd(14)} ${price}`);
    } catch (err) {
      console.log(`  fail ${symbol.padEnd(14)} ${err instanceof Error ? err.message : err}`);
    }
    await new Promise((r) => setTimeout(r, SPACING_MS));
  }

  for (const symbol of CHARTED) {
    try {
      const r = await chart(symbol, "1y", "1wk");
      const ts = r.timestamp ?? [];
      const closes =
        r.indicators?.adjclose?.[0]?.adjclose ??
        r.indicators?.quote?.[0]?.close ??
        [];
      const points: Array<{ t: number; close: number }> = [];
      for (let i = 0; i < ts.length; i++) {
        const c = closes[i];
        if (typeof c === "number" && Number.isFinite(c)) {
          points.push({ t: ts[i], close: c });
        }
      }
      if (points.length > 0) {
        series[symbol] = points;
        console.log(`  ok   series ${symbol.padEnd(10)} ${points.length} points`);
      }
    } catch (err) {
      console.log(`  fail series ${symbol.padEnd(10)} ${err instanceof Error ? err.message : err}`);
    }
    await new Promise((r) => setTimeout(r, SPACING_MS));
  }

  if (ok < symbols.length / 2) {
    console.error(`\nOnly ${ok} of ${symbols.length} symbols resolved. Snapshot not written.`);
    process.exit(1);
  }

  const body = `/**
 * Market snapshot.
 *
 * Generated by scripts/harvest-markets.mts. Do not edit by hand.
 *
 * The public quote endpoint rate-limits shared hosting networks and any
 * machine that bursts it, so both a serverless deployment and a workstation
 * mid-testing can be refused for minutes at a time. The application always
 * tries the live endpoint first, then the in-process last-known-good store,
 * and only then this file, labelled baseline with the date it was taken.
 *
 * Regenerate whenever the endpoint answers:
 *   node --experimental-strip-types scripts/harvest-markets.mts
 */

import type { Quote, SeriesPoint } from "@/lib/core/types";

export const MARKET_SNAPSHOT_TAKEN: string | null = ${JSON.stringify(new Date().toISOString())};

export const MARKET_SNAPSHOT_QUOTES: Record<string, Quote> = ${JSON.stringify(quotes, null, 2)};

export const MARKET_SNAPSHOT_SERIES: Record<string, SeriesPoint[]> = ${JSON.stringify(series, null, 2)};
`;

  writeFileSync("lib/data/market-snapshot.ts", body);
  console.log(`\nWrote lib/data/market-snapshot.ts: ${ok} quotes, ${Object.keys(series).length} series.`);
}

main();
