import { writeFileSync } from "node:fs";
import { IR_INDEXES, scrapeIr } from "@/lib/research/ir-scrape";
import { buildLedgerFromIr } from "@/lib/research/ir-facts";
import { getFxTable } from "@/lib/feeds/fx";
import { UNIVERSE } from "@/lib/data/universe";
import type { FactKey } from "@/lib/research/facts";

interface SnapshotPoint {
  end: string;
  label: string;
  value: number;
}

interface SnapshotSeries {
  tag: string;
  unit: string;
  annual: SnapshotPoint[];
  quarterly: SnapshotPoint[];
}

interface SnapshotEntry {
  symbol: string;
  name: string;
  indexUrl: string;
  filesRead: string[];
  sourceCurrency: string | null;
  rate: number | null;
  rateDate: string | null;
  series: Partial<Record<FactKey, SnapshotSeries>>;
}

const out: SnapshotEntry[] = [];
const fx = await getFxTable().catch(() => null);

console.log(`fx ${fx ? `${fx.asOf}, ${Object.keys(fx.rates).length} currencies` : "unavailable"}`);
console.log(`harvesting ${IR_INDEXES.length} investor relations indexes\n`);

for (const index of IR_INDEXES) {
  const company = UNIVERSE.find((c) => c.symbol === index.symbol);
  if (!company) {
    console.log(`${index.symbol.padEnd(15)} not in the coverage universe, skipped`);
    continue;
  }

  try {
    const scraped = await scrapeIr(index.symbol, 3);
    if (!scraped || scraped.metrics.length === 0) {
      console.log(`${index.symbol.padEnd(15)} no metric rows could be read`);
      continue;
    }

    const bridged = buildLedgerFromIr(scraped, fx, company.currency);
    if (!bridged) {
      console.log(
        `${index.symbol.padEnd(15)} ${scraped.metrics.length} rows read, none mapped onto a measure`,
      );
      continue;
    }

    const series: Partial<Record<FactKey, SnapshotSeries>> = {};
    for (const [key, line] of Object.entries(bridged.ledger.series)) {
      if (!line) continue;
      series[key as FactKey] = {
        tag: line.tag,
        unit: line.unit,
        annual: line.annual.map((p) => ({
          end: p.end,
          label: p.label,
          value: Number(p.value.toFixed(2)),
        })),
        quarterly: line.quarterly.map((p) => ({
          end: p.end,
          label: p.label,
          value: Number(p.value.toFixed(2)),
        })),
      };
    }

    out.push({
      symbol: index.symbol,
      name: index.name,
      indexUrl: scraped.indexUrl,
      filesRead: scraped.read.filter((r) => r.ok).map((r) => r.doc.filename),
      sourceCurrency: bridged.sourceCurrency,
      rate: bridged.rate,
      rateDate: bridged.rateDate,
      series,
    });

    console.log(
      `${index.symbol.padEnd(15)} ${String(bridged.mapped.length).padStart(2)} measures  ` +
        `${scraped.read.filter((r) => r.ok).length} files  ` +
        `${bridged.sourceCurrency ?? "?"}${bridged.rate ? ` at ${bridged.rate.toFixed(2)}` : ""}  ` +
        `[${bridged.mapped.slice(0, 8).join(" ")}${bridged.mapped.length > 8 ? " ..." : ""}]`,
    );
  } catch (err) {
    console.log(
      `${index.symbol.padEnd(15)} failed: ${err instanceof Error ? err.message.slice(0, 70) : String(err)}`,
    );
  }
}

const taken = new Date().toISOString();
const measures = out.reduce((s, e) => s + Object.keys(e.series).length, 0);

const banner = `/**
 * Published results files, harvested.
 *
 * Generated by scripts/harvest-ir-ledgers. Every figure here was read from the
 * company's own published spreadsheet or results release, at the date below.
 *
 * This is a fallback, not the source. The console fetches these documents live
 * on every request and uses what it gets; this is what it falls back to when a
 * publisher refuses the request, which several of them do to any connection
 * originating from a hosting provider rather than from an ordinary network.
 * Anything served from here is labelled with the harvest date, so a reader is
 * never shown a figure from this file as though it arrived this morning.
 *
 * Refresh with:
 *   npm run harvest:ir
 */

import type { FactKey } from "@/lib/research/facts";

export interface IrSnapshotSeries {
  tag: string;
  unit: string;
  annual: Array<{ end: string; label: string; value: number }>;
  quarterly: Array<{ end: string; label: string; value: number }>;
}

export interface IrSnapshotEntry {
  symbol: string;
  name: string;
  indexUrl: string;
  filesRead: string[];
  sourceCurrency: string | null;
  rate: number | null;
  rateDate: string | null;
  series: Partial<Record<FactKey, IrSnapshotSeries>>;
}

/** When this snapshot was taken. Shown wherever a figure from it is used. */
export const IR_LEDGER_TAKEN = ${JSON.stringify(taken)};

export const IR_LEDGER_SNAPSHOT: IrSnapshotEntry[] = `;

writeFileSync(
  "lib/data/ir-ledger-snapshot.ts",
  `${banner}${JSON.stringify(out, null, 0)};\n`,
);

console.log(
  `\nwrote lib/data/ir-ledger-snapshot.ts: ${out.length} companies, ${measures} measures, ` +
    `${(JSON.stringify(out).length / 1024).toFixed(0)} kB, taken ${taken.slice(0, 10)}`,
);
