/**
 * Investor relations snapshot generator.
 *
 * Several publishers refuse datacentre IP ranges, so the harvest succeeds from
 * a workstation and fails from a serverless host. Rather than lose the data,
 * this runs the harvest where it works and writes the result into the repo. The
 * application still attempts a live fetch first and only falls back to this
 * file, which is labelled with the date it was taken so nobody mistakes it for
 * a live figure.
 *
 * Run before a deploy:
 *   node --experimental-strip-types scripts/harvest-ir.mts
 */

import { writeFileSync } from "node:fs";
import { IR_SOURCES, parseIrQuarter, type IrQuarter } from "../lib/feeds/ir-parse.ts";
import { extractPdfText } from "../lib/pdf/extract.ts";

const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

const QUARTERS = 10;

async function main() {
  const out: Record<string, { name: string; irUrl: string; quarters: IrQuarter[] }> = {};

  for (const source of IR_SOURCES) {
    const refs = source.build(new Date(), QUARTERS);
    const quarters: IrQuarter[] = [];

    console.log(`\n${source.name}`);
    for (const ref of refs) {
      try {
        const res = await fetch(ref.url, {
          headers: {
            "User-Agent": UA,
            Accept: "text/html,application/xhtml+xml,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
            "Sec-Fetch-Dest": "document",
            "Sec-Fetch-Mode": "navigate",
            "Sec-Fetch-Site": "none",
            "Upgrade-Insecure-Requests": "1",
          },
        });

        if (!res.ok) {
          console.log(`  ${ref.label.padEnd(10)} HTTP ${res.status}`);
          continue;
        }

        const bytes = new Uint8Array(await res.arrayBuffer());
        const parsed = parseIrQuarter(extractPdfText(bytes).lines, ref);

        if (parsed.confidence >= 0.4) {
          quarters.push(parsed);
          console.log(
            `  ${ref.label.padEnd(10)} ok   rev $${parsed.revenueUsdMn}mn  ` +
              `op ${parsed.operatingMarginPct}%  head ${parsed.headcount}  ` +
              `conf ${parsed.confidence.toFixed(2)}`,
          );
        } else {
          console.log(
            `  ${ref.label.padEnd(10)} thin (${Math.round(parsed.confidence * 100)}% of fields)`,
          );
        }
      } catch (err) {
        console.log(`  ${ref.label.padEnd(10)} ${err instanceof Error ? err.message : err}`);
      }
      await new Promise((r) => setTimeout(r, 400));
    }

    quarters.reverse();
    out[source.symbol] = { name: source.name, irUrl: source.irUrl, quarters };
  }

  const total = Object.values(out).reduce((n, v) => n + v.quarters.length, 0);
  if (total === 0) {
    console.error("\nNo quarters harvested. Snapshot not written.");
    process.exit(1);
  }

  const body = `/**
 * Investor relations snapshot.
 *
 * Generated by scripts/harvest-ir.mts. Do not edit by hand.
 *
 * These publishers refuse datacentre IP ranges, so a deployed instance cannot
 * fetch them. The application attempts a live fetch on every request and uses
 * this file only when that fails, labelling the result with the date below.
 *
 * Regenerate before a deploy:
 *   node --experimental-strip-types scripts/harvest-ir.mts
 */

import type { IrQuarter } from "@/lib/feeds/ir-parse";

export const IR_SNAPSHOT_TAKEN = ${JSON.stringify(new Date().toISOString().slice(0, 10))};

export const IR_SNAPSHOT: Record<
  string,
  { name: string; irUrl: string; quarters: IrQuarter[] }
> = ${JSON.stringify(out, null, 2)};
`;

  writeFileSync("lib/data/ir-snapshot.ts", body);
  console.log(`\nWrote lib/data/ir-snapshot.ts with ${total} quarters.`);
}

main();
